spring:
  kafka:
    bootstrap-servers: localhost:29092,myVMsIP:9094
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        schema.registry.url: http://localhost:8081,http://myVMsIP:8081

    consumer:
      group-id: avro-consumer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://localhost:8081,http://myVMsIP:8081
        specific.avro.reader: true
